name: "Remove"
description: "파일을 삭제하는 작업만 수행할 때 사용합니다."
title: "Remove: "
labels: ["Remove"]
projects:
  - "hobby-picker/찍먹 server kanban"
type: Task
body:
  - type: textarea
    id: overview
    attributes:
      label: "Issue 요약"
      placeholder: "예: 미사용 이미지 파일 삭제"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Issue 상세"
      placeholder: "예: 레거시 로고 이미지를 삭제합니다."
  - type: textarea
    id: todo
    attributes:
      label: "To do"
      placeholder: "예: - [ ] legacy_logo.png 삭제"